src/PiLights/Models/Alert.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PiLights.Models
{
    /// <summary>
    /// Details about the contents of an individual alert that should be displayed
    /// to the user in a view.
    /// </summary>
    public class Alert
    {
        /// <summary>
        /// Gets or sets the HTML message content.
        /// </summary>
        /// <value>
        /// A <see cref="string"/> with the full content for the alert.
        /// The content may contain HTML for additional formatting within the alert.
        /// </value>
        public string MessageHtml { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the alert is a success message.
        /// </summary>
        /// <value>
        /// <see langword="true"/> if the alert is a success message; otherwise,
        /// <see langword="false"/>.
        /// </value>
        public bool Success { get; set; }
    }
}

src/PiLights/Models/ConfigurationModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PiLights.Models
{
    public class ConfigurationModel
    {
        public int LedCount { get; set; }

        public LedType LedType { get; set; }

        public string ServerIP { get; set; }

        public int ServerPort { get; set; }
    }
}

src/PiLights/Models/ErrorViewModel.cs
using System;

namespace PiLights.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(this.RequestId);
    }
}

src/PiLights/Models/GlobalConfigurationSettings.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace PiLights.Models
{
    public class GlobalConfigurationSettings
    {
        [DisplayName("Global Brightness")]
        [Range(1, 255)]
        [Required]
        public int GlobalBrightness { get; set; }

        [DisplayName("LED Count")]
        [Range(1, int.MaxValue)]
        [Required]
        public int LedCount { get; set; }

        [DisplayName("LED Type")]
        [Required]
        [DataType("Enum")]
        public LedType LedType { get; set; }

        [DisplayName("Server IP Address")]
        [Required]
        public string ServerIP { get; set; }

        [DisplayName("Server Port")]
        [Range(1, 32767)]
        [Required]
        public int ServerPort { get; set; }
    }
}

src/PiLights/Models/LedType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PiLights.Models
{
    public enum LedType
    {
        /// <summary>
        /// WS2811 RGB
        /// </summary>
        WS2811_STRIP_RGB,

        /// <summary>
        /// WS2811 RBG
        /// </summary>
        WS2811_STRIP_RBG,

        /// <summary>
        /// WS2811 GRB
        /// </summary>
        WS2811_STRIP_GRB,

        /// <summary>
        /// WS2811 GBR
        /// </summary>
        WS2811_STRIP_GBR,

        /// <summary>
        /// WS2811 BRG
        /// </summary>
        WS2811_STRIP_BRG,

        /// <summary>
        /// WS2811 BGR
        /// </summary>
        WS2811_STRIP_BGR,

        /// <summary>
        /// SK6812 RGBW
        /// </summary>
        SK6812_STRIP_RGBW,

        /// <summary>
        /// SK6812 RBGW
        /// </summary>
        SK6812_STRIP_RBGW,

        /// <summary>
        /// SK6812 GRBW
        /// </summary>
        SK6812_STRIP_GRBW,

        /// <summary>
        /// SK6812 GBRW
        /// </summary>
        SK6812_STRIP_GBRW,

        /// <summary>
        /// SK6812 BRGW
        /// </summary>
        SK6812_STRIP_BRGW,

        /// <summary>
        /// SK6812 BGRW
        /// </summary>
        SK6812_STRIP_BGRW,
    }
}

src/PiLights/Models/PlugStatus.cs
using System;
using System.Linq;

namespace PiLights.Models
{
    public class PlugStatus
    {
        public bool On { get; set; }
    }
}

src/PiLights/Controllers/ConfigurationController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using PiLights.Configuration;

namespace PiLights.Controllers
{
    public class ConfigurationController : Controller
    {
        private readonly LedSettings _configuration;

        public ConfigurationController(LedSettings configuration)
        {
            this._configuration = configuration ?? throw new ArgumentNullException(nameof(configuration));
        }

        [HttpGet]
        public IActionResult Index()
        {
            return this.View(this._configuration);
        }
    }
}

src/PiLights/Controllers/ErrorController.cs
using System;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using PiLights.Models;

namespace PiLights.Controllers
{
    public class ErrorController : Controller
    {
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Index()
        {
            return this.View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }
    }
}

src/PiLights/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using PiLights.Models;
using PiLights.Properties;
using PiLights.Scenes;

namespace PiLights.Controllers
{
    public class HomeController : Controller
    {
        public HomeController(IEnumerable<Scene> scenes)
        {
            this.Scenes = scenes ?? throw new ArgumentNullException(nameof(scenes));
        }

        public IEnumerable<Scene> Scenes { get; private set; }

        [HttpGet]
        public IActionResult Index()
        {
            this.ViewBag.Scenes = this.Scenes.Select(x => new SelectListItem { Text = x.GetDisplayName(), Value = x.GetType().FullName });
            return this.View();
        }

        [HttpPost]
        public IActionResult SceneProperties(string sceneName)
        {
            var scene = this.Scenes.First(x => x.GetType().FullName == sceneName);
            return this.PartialView(scene);
        }

        [HttpPost]
        public async Task<IActionResult> StartScene(string sceneName)
        {
            var scene = this.Scenes.First(x => x.GetType().FullName == sceneName);
            if (!await this.TryUpdateModelAsync(scene, scene.GetType(), string.Empty))
            {
                this.ModelState.AddModelError(string.Empty, Resources.Home_BindError);
            }
            else if (!this.TryValidateModel(scene))
            {
                this.ModelState.AddModelError(string.Empty, Resources.Home_ValidateError);
            }

            if (!this.ModelState.IsValid)
            {
                return this.PartialView(scene);
            }

            this.SetAlert(scene.Execute());
            return this.RedirectToAction(nameof(this.Index));
        }

        private void SetAlert(bool success)
        {
            var alert = new Alert { MessageHtml = success ? Resources.Home_SceneSuccess : Resources.Home_SceneFail, Success = success };
            this.HttpContext.Session.SetString("alert-message", JsonConvert.SerializeObject(alert));
        }
    }
}

src/PiLights/Controllers/PowerController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PiLights.Models;
using PiLights.Services;

namespace PiLights.Controllers
{
    public class PowerController : Controller
    {
        public PowerController(IPlugController plugController)
        {
            // TODO: JS polling from the front end for status
            // https://davidwalsh.name/javascript-polling
            // TODO: Click power button to turn on/off, confirm when turning off.
            this.PlugController = plugController ?? throw new ArgumentNullException(nameof(plugController));
        }

        public IPlugController PlugController { get; private set; }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Shutdown()
        {
            await this.PlugController.ShutdownAsync();
            return this.Ok();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Startup()
        {
            await this.PlugController.StartupAsync();
            return this.Ok();
        }

        [HttpGet]
        public async Task<ActionResult<PlugStatus>> Status()
        {
            return await this.PlugController.StatusAsync();
        }
    }
}

src/PiLights/Views/Configuration/Index.cshtml
@model PiLights.Configuration.LedSettings

@{
    ViewData["Title"] = "Configuration";
}

<div class="container">
    <div class="row">
        <div class="col-sm">
            <h1>Current Configuration Settings</h1>
            <p>Change settings by modifying <code>appsettings.json</code> or setting configuration environment variables like <code>WS281X__PORT</code>.</p>
            <fieldset class="panel border rounded">
                @Html.DisplayForModel()
            </fieldset>
        </div>
    </div>
</div>

src/PiLights/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <div class="row">
        <div class="col-sm">
            <h1>Scene Settings</h1>
            <form id="scene" asp-controller="home" asp-action="StartScene" method="post">
                <fieldset class="panel border rounded">
                    <alerts></alerts>
                    <div class="form-group">
                        <label for="sceneName">Scene</label>
                        <select id="sceneName" name="sceneName" asp-items="this.ViewBag.Scenes" class="form-control" autocomplete="off" autofocus="autofocus">
                            <option disabled selected>--- SELECT ---</option>
                        </select>
                    </div>
                    <div id="sceneProperties" style="display:none;"></div>
                </fieldset>
            </form>
        </div>
    </div>
 </div>

@section scripts
{
    <script>
        $('#sceneName').change(function () {
            $("div[role='alert']").hide();
            var selected = $(this).val();
            var postData = {
                sceneName: selected
            };
            $.ajax({
                url: '/Home/SceneProperties',
                type: 'POST',
                cache: false,
                async: true,
                dataType: "html",
                data: postData
            })
            .done(function (result) {
                $('#sceneProperties').html(result);
                $('#sceneProperties').fadeIn('fast');
            }).fail(function (xhr) {
                console.log('error : ' + xhr.status + ' - ' + xhr.statusText + ' - ' + xhr.responseText);
            }); 
            
        });

        $(document).on("submit", "#start", function () {
            $(this).prop("disabled", true);
            $(this).addClass("disabled");
        });
    </script>
}

src/PiLights/Views/Home/SceneProperties.cshtml
@using System.Reflection;
@using PiLights.Scenes;
@model Scene

<input hidden="hidden" name="sceneName" value="@Model.GetType().FullName" />

@Html.EditorForModel()
<div class="form-group">
    <button type="submit" name="start" id="start" data-clear-alerts="true" class="btn btn-primary">Apply</button>
</div>

src/PiLights/Views/Shared/DisplayTemplates/Boolean.cshtml
@model System.Boolean?

@Html.CheckBox("", this.Model, new { @class = "form-check-input", disabled = "true" })

src/PiLights/Views/Shared/DisplayTemplates/Color.cshtml
@using PiLights.Scenes
@model System.Drawing.Color

@Html.TextBox("", this.Model.ToHexColor(), new { type = "color", @class="form-control", disabled = "true" })

src/PiLights/Views/Shared/DisplayTemplates/Enum.cshtml
@model Enum

<div class="form-control">@this.Model.ToString()</div>

src/PiLights/Views/Shared/DisplayTemplates/Int32.cshtml
@model System.Int32

<div class="form-control">@this.Model</div>

src/PiLights/Views/Shared/DisplayTemplates/Object.cshtml
@model System.Object
@using PiLights.Services

@ObjectDisplayTemplate.ObjectTemplate(this.Html)

src/PiLights/Views/Shared/DisplayTemplates/String.cshtml
@model System.String

<div class="form-control">@this.Model</div>

src/PiLights/Views/Shared/EditorTemplates/Boolean.cshtml
@model System.Boolean?

@Html.CheckBox("", this.Model, new { @class = "form-check-input" })

src/PiLights/Views/Shared/EditorTemplates/Color.cshtml
@using PiLights.Scenes
@model System.Drawing.Color

@Html.TextBox("", this.Model.ToHexColor(), new { type = "color", @class="form-control" })

src/PiLights/Views/Shared/EditorTemplates/Enum.cshtml
@model Enum

@{

    var values = Enum.GetValues(ViewData.ModelMetadata.ModelType).Cast<object>()
                     .Select(v => new SelectListItem
                     {
                         Selected = v.Equals(Model),
                         Text = v.ToString(),
                         Value = v.ToString()
                     });
}

@Html.DropDownList("", values, new { @class="form-control" })

src/PiLights/Views/Shared/EditorTemplates/Int32.cshtml
@model System.Int32

@Html.TextBox("", this.Model, new { type = "number", @class = "form-control" })

src/PiLights/Views/Shared/EditorTemplates/Object.cshtml
@model System.Object
@using PiLights.Services

@ObjectEditorTemplate.ObjectTemplate(this.Html)

src/PiLights/Views/Shared/EditorTemplates/String.cshtml
@model System.String

@Html.TextBox("", this.Model, new { @class = "form-control" })

src/PiLights/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - Pi Lights</title>
    <partial name="_Stylesheets" />
    <environment include="Development">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Pi Lights</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a asp-area="" asp-controller="Configuration" asp-action="Index" class="nav-link">Configuration</a>
                    </li>
                </ul>
            </div>
            <form class="form-inline mt-2 mt-md-0" id="powerForm" method="post" asp-controller="Power" asp-action="Shutdown">
                @Html.AntiForgeryToken()
                <button class="material-icons md-light nav-link power-off-button" style="display:none" data-toggle="modal" data-target="#powerOffModal" type="button">power_settings_new</button>
                <button class="material-icons md-dark nav-link power-on-button" style="display:none" data-toggle="modal" data-target="#powerOnModal" type="button">power_settings_new</button>
            </form>
        </nav>
    </header>
    <main role="main">
        @RenderBody()
    </main>

    <partial name="_Scripts" />
    <partial name="_PowerModal" />
    @RenderSection("Scripts", required: false)
</body>
</html>

src/PiLights/Views/Shared/_PowerModal.cshtml
<div class="modal fade" id="powerOffModal" tabindex="-1" role="dialog" aria-labelledby="powerOffModalTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="powerOffModalTitle">Power Off?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to power down?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary power-confirm">Power Off</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="powerOnModal" tabindex="-1" role="dialog" aria-labelledby="powerOnModalTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="powerOnModalTitle">Power On?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Would you like to power on?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary power-confirm">Power On</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<script>
$('.power-confirm').click(function () {
    $('#powerForm').submit();
});
</script>

src/PiLights/Views/Shared/_Scripts.cshtml
<environment include="Development">
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.2.1/js/bootstrap.min.js"
            asp-fallback-src="~/lib/twitter-bootstrap/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha256-63ld7aiYP6UxBifJWEzz87ldJyVnETUABZAYs5Qcsmc=">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

src/PiLights/Views/Shared/_Stylesheets.cshtml
<environment include="Development">
    <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
</environment>
<environment exclude="Development">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.2.1/css/bootstrap.min.css"
          asp-fallback-href="~/lib/twitter-bootstrap/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
</environment>